spring.application.name=Secure_Token

# Conexión a SQLite
spring.datasource.url=jdbc:sqlite:cibergu_database.sqlite
spring.datasource.driver-class-name=org.sqlite.JDBC

# Configuración de Hibernate para usar el dialecto de SQLite
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Ignorar advertencias de JPA incompatibles con SQLite
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false